# Ten-Agent CLI Releaser
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: . # use main.go in the root directory

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: '{{ incpatch .Version }}-next'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - name: ten-agent-cli
    repository:
      owner: digitallysavvy
      name: homebrew-tap
      token: '{{ .Env.TAP_GITHUB_TOKEN }}'
    homepage: 'https://github.com/digitallysavvy/ten-agent-cli'
    description: 'CLI tool for TEN-Agent'
    license: 'Apache-2.0'
    commit_author:
      name: TEN-Agent CLI Bot
      email: noreply@digitallysavvy.com
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
